export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';

export const PURCHASE_SUC = 'PURCHASE_SUC';
export const PURCHASE_FAIL = 'PURCHASE_FAIL';
export const PURCHASE_STATE = 'PURCHASE_STATE';
export const PURCHASE_INIT = 'PURCHASE_INIT';

export const ORDER_START = 'ORDER_START';
export const ORDER_FAIL = 'ORDER_FAIL';
export const ORDER_SUC = 'ORDER_SUC';

export const AUTH_SUC = 'AUTH_SUC';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_START = 'AUTH_START';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const AUTH_REDIRECT_PATH = 'AUTH_REDIRECT_PATH';